name: Remover Workflow

on:
  workflow_dispatch:  # Permite rodar manualmente no GitHub Actions

jobs:
  delete-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar usuário do Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: deploy.yml
        run: |
          git rm .github/workflows/deploy.yml|| echo "Arquivo já removido"
          git commit -m "Removendo workflow automaticamente"
          git push origin main
