name: CI/CD for React

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test -- --watchAll=false

      - name: Construir a aplicação
        run: npm run build

      - name: Armazenar artefato da aplicação
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/

  deploy-test:
    needs: build
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build/

      - name: Deploy para ambiente de teste
        run: echo "Fazendo deploy no ambiente de teste..."

  deploy-production:
    needs: deploy-test
    runs-on: ubuntu-latest
    environment: production  # 🔹 Garante que precisa de aprovação manual
    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build/

      - name: Deploy para produção
        run: echo "Fazendo deploy para produção..."
