name: Deploy na Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar Vercel CLI
        run: npm install -g vercel

      - name: Autenticar na Vercel
        run: vercel login --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy para a Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
