name: Deploy para Vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v20
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Construir aplicação
        run: npm run build

      - name: Upload do Artefato
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production  # Configurar para exigir aprovação
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar CLI da Vercel
        run: npm install -g vercel

      - name: Deploy na Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
